# Azure CLI Action
name: 'Azure CLI Action'
description: 'Automate your GitHub workflows using Azure CLI scripts.'
inputs:
  inlineScript:
    description: 'Specify the script here'
    required: true
  azcliversion:
    description: 'Azure CLI version to be used to execute the script. If not provided, the version on the agent is used. '
    required: false
    default: 'agentazcliversion'
branding:
  icon: 'login.svg'
  color: 'blue'
runs:
  using: 'node20'
  main: 'dist/index.js'
